service: graphql-api

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpackIncludeModules: true
  dynamodb:
    start:
      port: 8001
      migrate: true
  serverless-offline:
    noAuth: true
    port: 3001

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:eu-central-1:*:*

functions:
  graphql:
    handler: lib/handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: aws_iam
  graphiql:
    handler: lib/handler.graphiql
    events:
      - http:
          path: graphiql
          method: get
          cors: true
resources:
  Resources:
    EntriesDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: 'entries'
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createDate
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: createDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    AttachmentsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: 'attachments'
        AttributeDefinitions:
          - AttributeName: entryId
            AttributeType: S
          - AttributeName: position
            AttributeType: N
        KeySchema:
          - AttributeName: entryId
            KeyType: HASH
          - AttributeName: position
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
